### ISSUE TITLE
Remove Block Grid SCSS from _global.scss

### ISSUE THREAD

**Issue by erwstout** [factor1/Prelude#41]
Following code is in `_global.scss`:

```scss
[class*="block-grid-"] > li {
  //fix margins on block grids inside of articles
  margin : 0;
}

[class*="block-grid-"] {
  margin : 0;
}
```

This was to support/fix an issue in Foundation 5, which we no longer use.  Should we leave this for legacy support or remove?

@factor1/staff
