### ISSUE TITLE
Change `html,body` height property in `global.scss`

### ISSUE THREAD

**Issue by erwstout** [factor1/Prelude#43]
There is a css property that can cause scroll issues located in `_global.scss` .

```scss
html,
body {
  border  : 0;
  margin  : 0;
  padding : 0;
  width   : 100%;
  height  : 100%;
}
```

But should be:

```scss
html,
body {
  border  : 0;
  margin  : 0;
  padding : 0;
  width   : 100%;
  min-height  : 100%;
}
```
